### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by elifoster** [elifoster/SantasMods#9]
For some reason, when in a dev environment (post build not tested), new resources are not loaded. This includes lang stuff and textures. Old ones are not effected, weirdly. Currently using IntelliJ IDEA CE 14 with the resources folder set as the Resource Directory.

**Comment by williewillus** [comment]
Add ```idea.module.inheritOutputDirs = true``` to build.gradle and resetup your build environment

For IDEA, all you need to do to setup a dev env is ```gradle setupDecompWorkspace```
Then go to import project in IDEA, and select build.gradle file.
Then run task ```genIntellijRuns``` from the IDEA Gradle sidebar

**Comment by elifoster** [comment]
Okay, I'll do that in a little bit.

And yes I know how to set up a dev environment with IDEA :laughing: I've been doing this a long time, just never run into this specific issue.

**Comment by williewillus** [comment]
was just making sure :p some tutorials still tell people to use the old gradle idea task, which doesnt work for idea 14+

**Comment by elifoster** [comment]
With the new dev environment I have, this is fixed.
